version: '3'
services:

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/data:/opt
    ports:
      - "$PGPORT:5432"

  sqitch:
    image: "sqitch/sqitch:latest"
    container_name: sqitch
    env_file:
      - .env
    environment:
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
    volumes:
      - ./src/migrations/sqitch:/repo

  flyway:
    build: "./src/applications/flyway"
    container_name: flyway
    env_file:
      - .env
    command: bash -c "flyway migrate -locations=filesystem:/flyway/migrations/flyway -schemas=flyway -connectRetries=60"
    environment:
      - FLYWAY_URL=jdbc:postgresql://$PGHOST:$PGPORT/$PGDATABASE
      - FLYWAY_USER=$PGUSER
      - FLYWAY_PASSWORD=$PGPASSWORD
    volumes:
      - ./src/migrations:/flyway/migrations
